name: Tests

on: [push, pull_request]

jobs:
  build:
    uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@main
    with:
      oci-archive-name: "curl-rock"
      rock-repo: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name || github.repository }}
      rock-repo-commit: ${{ github.event_name == 'push' && github.ref_name || github.head_ref }}
      rockfile-directory: 8.5.0
      arch-map: '{"amd64": "ubuntu-latest"}'

  test:
    uses: canonical/oci-factory/.github/workflows/Test-Rock.yaml@main
    needs: 
      - build
    with:
      oci-archive-name: "curl-rock"

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/download-artifact@v4
        with:
          name: curl-rock

      - name: 'Set up skopeo'
        uses: warjiang/setup-skopeo@main
        with:
          version: latest

      - run: skopeo copy --multi-arch all oci-archive:curl-rock docker://ghcr.io/rockcrafters/curl-rock/curl:latest